### ISSUE TITLE
Issue with AppCode 2017.2.3 EAP

### ISSUE THREAD

**Issue by amseddi** [seanhenry/MockGenerator#10]
message : com.jetbrains.swift.psi.SwiftParameter.getParameterTypeAnnotation()Lcom/jetbrains/swift/psi/SwiftParameterTypeAnnotation;

**Comment by seanhenry** [comment]
Thanks @amseddi !

It seems that JetBrains have changed the ownership of parameter type-annotations to the type rather than the parameter which sounds sensible.  

I've fixed this issue and uploaded a pre-release build to the [releases](https://github.com/seanhenry/MockGenerator/releases/tag/7-beta) page. You can manually install the JAR found there. I'll submit a build to JetBrains when 2017.2.3 is released since this will drop support for 2017.2.2 and below.

I also found that `inout` parameter types weren't supported so added support for those too 🎉

**Comment by amseddi** [comment]
Thanks @seanhenry ! The new release works perfectly :)
