### ISSUE TITLE
Reset Spy between runs

### ISSUE THREAD

**Issue by pikaboo** [seanhenry/MockGenerator#20]
If i have multiple tests that use the same instance of mock, i get fails for the number of times a method was invoked for example

Need a reset method that will send the spy back to initial state

**Comment by seanhenry** [comment]
Hi @pikaboo 

Thanks for this suggestion. One of the reasons this feature isn't there is because I would like to keep the generated code simple and in a handwritten style so that you can generate these test doubles without requiring the whole development team to adopt this plugin. Adding a reset method would make the generated code impossible to maintain without everyone using this plugin.

A simple solution to the problem is to just recreate the mock in the `setUp` or `beforeEach` part of your test run.

Another solution is to create your own template to generate your own mock objects ([see here](https://github.com/seanhenry/MockGenerator/issues/14)). The functionality isn't there yet but I will add that feature if you will use it.

**Comment by seanhenry** [comment]
I'm hoping you're ok with the above solution. If not, feel free to reopen this issue :)
