### ISSUE TITLE
Bash script support

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/MockGenerator#9]
Is there any way to separate the plugin in a bash script/separate binary? AppCode is not free, but I would love to use the plugin either as a separate executable binary or Xcode plugin.

**Comment by seanhenry** [comment]
@LeonidKokhnovich Thanks for raising this issue. I spent some time over the last couple of days trying to figure out whether this is possible. 

I've created a very basic proof of concept Xcode plugin which seems to work OK. The problem is the engine that Xcode uses to resolve Swift code is much more difficult to use than AppCode's so there will be significant extra work to do to get this to work. 

I'll continue to look into this and post updates here.

In the meantime, if anyone else is interested in an Xcode plugin to generate mocks, please comment to give me an idea of how many people will use this. The more interest, the more time I can allocate to this.

**Comment by LeonidKokhnovich** [comment]
@seanhenry Thank you a lot for looking into it. What version of Xcode did you use for proof-of-concept?

**Comment by abbeyjackson** [comment]
@seanhenry  +1 for me!

**Comment by seanhenry** [comment]
@LeonidKokhnovich I'm looking at Xcode 8.3.2 with the intent of moving to Xcode 9 when it's released. 

Thanks @abbeyjackson

Quick update: I'm working on an Xcode plugin beta release. It won't be as feature rich as the AppCode plugin but it will aim to provide:
- mock classes that compile
- method invocation checks
- method invocation check counts

**Comment by LeonidKokhnovich** [comment]
@seanhenry Thank you! I can test it on my side once you think it's ready.

**Comment by seanhenry** [comment]
@LeonidKokhnovich @abbeyjackson I've uploaded the first beta release for the Xcode plugin in a new [GitHub repo](https://github.com/seanhenry/SwiftMockGeneratorForXcode). 

Your feedback would be greatly appreciated!

I will close this issue here. Feel free to open any issues on the new repo.

Happy mocking!

**Comment by amseddi** [comment]
Hi @seanhenry 

I recently came across this tool: https://github.com/krzysztofzablocki/Sourcery which is very useful to generate Swift code like `Equatable` conformance.

And maybe Xcode users can have all the features by using a Sourcery template 🤔

**Comment by seanhenry** [comment]
They have a mock template too which could be modified https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoMockable.stencil
